# Pre-commit hook configuration
# https://pre-commit.com/

repos:
  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Trailing whitespace
      - id: trailing-whitespace
        name: Trim trailing whitespace

      # End of file
      - id: end-of-file-fixer
        name: Fix end of files

      # YAML validation
      - id: check-yaml
        name: Check YAML

      # JSON validation
      - id: check-json
        name: Check JSON

      # Merge conflict markers
      - id: check-merge-conflict
        name: Check merge conflicts

      # Large files
      - id: check-added-large-files
        name: Check large files
        args: ['--maxkb=1000']

      # Case conflicts
      - id: check-case-conflict
        name: Check case conflicts

  # Python formatting with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Ruff formatter (replaces black)
      - id: ruff-format
        name: Format with ruff
        types_or: [python, pyi]

      # Ruff linter
      - id: ruff
        name: Lint with ruff
        args: ['--fix']

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.0'
    hooks:
      - id: bandit
        name: Security check with bandit
        args: ['-c', 'pyproject.toml']
        exclude: ^tests/

  # Test runner (local)
  - repo: local
    hooks:
      - id: pytest-check
        name: Run tests
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        files: '\.py$'

      # Quick test for modified files only
      - id: pytest-changed
        name: Test changed files
        entry: bash -c 'python -m pytest --tb=short $(git diff --cached --name-only | grep -E "\.py$" | sed "s|^|tests/unit/test_|" | sed "s|\.py$|.py|" | xargs -r ls 2>/dev/null || echo ".claude/tests/unit/")'
        language: system
        pass_filenames: false
        stages: [pre-push]

# Configuration
default_language_version:
    python: python3.12

# Stages configuration
default_stages: [pre-commit, pre-push]

# Exclude patterns
exclude: |
    (?x)(
        ^\.git/|
        ^\.cache/|
        ^\.ccache/|
        ^__pycache__/|
        ^\.pytest_cache/|
        ^\.coverage|
        ^htmlcov/|
        ^dist/|
        ^build/|
        ^.*\.egg-info/|
        ^venv/|
        ^\.env
    )

# CI skip configuration
ci:
    skip: [pytest-check, pytest-changed]
    autofix_prs: true
    autofix_commit_msg: '[pre-commit.ci] auto fixes from hooks'
