name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be better if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like to have...
        This feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        Alternative approach 1: ...
        Alternative approach 2: ...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New agent capability
        - Script enhancement
        - Documentation improvement
        - Developer experience (DX)
        - Performance optimization
        - Security enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        Use case 1: ...
        Use case 2: ...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Screenshots, diagrams, code examples, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these checks before submitting
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I am willing to contribute to implementing this feature
          required: false
