blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/sougetuOte/claude-friends-templates/discussions
    about: For questions, ideas, and general discussion about the project
  - name: 🔒 Security Issues
    url: https://github.com/sougetuOte/claude-friends-templates/security/advisories/new
    about: Report security vulnerabilities privately (do not create public issues)
  - name: 📖 Documentation
    url: https://github.com/sougetuOte/claude-friends-templates#readme
    about: Read the project documentation for help and guidance
